Fix `checkbox-cli check-config` throwing `AttributeError`
Running `checkbox-cli check-config` throws:

    $ checkbox-cli check-config
    Traceback (most recent call last):
    File "/home/meribold/git/checkbox-ng/venv/bin/checkbox-cli", line 11, in <module>
        load_entry_point('checkbox-ng', 'console_scripts', 'checkbox-cli')()
    File "/home/meribold/git/checkbox-ng/checkbox_ng/launcher/checkbox_cli.py", line 99, in main
        subcmd.register_arguments(subcmd_parser)
    AttributeError: 'CheckConfig' object has no attribute 'register_arguments'

This has presumably been the case since 13c043d0470d972284bb1a91c5b78bb,
which changed the `CheckConfig` class to no longer derive from
Guacamole's `Command` class.