Fix crash (TypeError exception) when resuming a session (#657)
* Fix crash (TypeError exception) when resuming a session

shlex.join() takes an iterable as a parameter. However, when using the
append() function from a list, nothing is returned, so shlex.join() will
raise the following exception:

TypeError: 'NoneType' object is not iterable

Instead, use the + operator to join two lists to avoid the problem.

Fix #654

* Add tests for _configure_restart

Minor: Explicitly ignore unused return

* Fixed shlex has no join on python<3.8

* assert_called is 3.6+

---------

Co-authored-by: Devices Certification Bot <robot@canonical.com>