Revert "Update namespace of provider to contrib"
This reverts commit 0f42780309737b1b40bbae5b27c633635682295a.

Updating the namespace starts to fail validation with errors like:

error: units/jobs.pxu:4: job 'intel_gpu/host_gpu_avail', field
'requires', unit 'com.canonical.contrib::executable' is not available