Migrate checkbox-dss-validation to checkbox/contrib (New) (#1524)
* Add most of checkbox-dss-validation content into contrib

* the original source repo was at commit bc07d01:
  <https://github.com/canonical/checkbox-dss-validation/tree/bc07d017e32706fd1578c0982c50d997ed8d47ac>.

* the following directories or their contents were NOT copied
  - .github
  - checkbox-provider-dss/bin : because it had binary files, not used anywhere

* no other modifications were made to the copied files

* Remove mention of gh workflows and relevant badge

* Update instructions to use this repo

* Update namespace of provider to contrib

* Revert "Update namespace of provider to contrib"

This reverts commit 0f42780309737b1b40bbae5b27c633635682295a.

Updating the namespace starts to fail validation with errors like:

error: units/jobs.pxu:4: job 'intel_gpu/host_gpu_avail', field
'requires', unit 'com.canonical.contrib::executable' is not available

* Add solutions-qa as codeowner for checkbox-dss-validation

* Add copy of testflinger job definition

* Update job def to use checkbox repo

* Add copy of DSS regression testing gh workflow

* Disable running DSS regression tests automatically

* Fix working directory for DSS regression workflow

* Add solutions-qa as codeowner for DSS regression

* Fix formatting of dss provider's manage.py

* Change names and description of provider per review

* Change namespace of DSS provider to contrib

As described in the readme, providers in the contrib area must have a
namespace that includes the word contrib.

Switching from `com.canonical.certification` to `com.canonical.contrib`.

This means that jobs and test plans from the base providers need to be
prefixed with the `com.canonical.certification` namespace.

* Fix namespace in test plan

---------

Co-authored-by: Pierre Equoy <pierre.equoy@canonical.com>