Fix importing issue when running unit tests
Due to how unit tests import packages at test time, the following error
shows up when running `./manage.py test -u` on the base provider:

ImportError: No module named 'dbus.exceptions'; 'dbus' is not a package

Since this module is not required for the tests, it is mocked to allow
the tests to run.