plainbox:vendor: add back-port of enum from python
This patch adds a vendorized copy of the implementation of PEP 435, aka
the Enum and IntEnum classes, from Python trunk. Enums are a nice
complement to our existing Symbol and SymbolDef classes and can be used
to gradually replace all ad-hoc enumerations with proper code.

Since the code is a part of the Python standard library it can be
dropped later, once we can require Python 3.4.  All of the code copied
from Python was written by Ethan Furman <ethan@stoneleaf.us> and is
available under the PSFv2 license.

This patch also makes two changes required to make the
otherwise-vanilla copy of enum from work on Python 3.2.

The first change is to expose the PyDictProxy_New C-API function as the
replacement for the types.MappingProxyType (also known as a read-only
dictionary). This internal type was exposed in Python 3.3. See
https://docs.python.org/3/library/types.html#types.MappingProxyType for
more details. Since the function is supported on Python 3.2 it can be
accessed manually using ctypes.

The second change is to provide a vanilla copy of DynamicClassAttribute,
straight from Python 3.4. It is a regular piece of Python code and it
does not depend on anything that is missing on Python 3.2.

There are no unit tests since I wasn't able to make the original python
test suite pass. The remaining failures are related to ongoing
improvements to the ``inspect`` module and to the changes introduced by not having __qualname__.
In my rudimentary testing we are not negatively impacted by either.

For reference, the list of failures is printed below. This was obtained with
test_enum.py from revision d19cdc1c09392ae3c578989bf1ca3baa96427928 patched to
import plainbox.vendor.enum instead of enum and patched once again to
monkey-patch the trunk version of inspect.getmembers instead of the version
used in python 3.2. I have decided not to include this modified version as it
doesn't improve the situation in any meaningful way, IMHO.

(venv.lucayan)zyga@lucayan:~/host$ python3 test_enum.py
.............................................................................E.............
===========================================================================
Attribute(name='__class__', kind='data', defining_class=<class 'object'>, object=<attribute '__class__' of 'object' objects>)
Attribute(name='__class__', kind='data', defining_class=<class 'object'>, object=<class 'plainbox.vendor.enum.EnumMeta'>)
===========================================================================

===========================================================================
Attribute(name='__members__', kind='data', defining_class=None, object=dict_proxy(OrderedDict([('red', <Color.red: 1>), ('green', <Color.green: 2>), ('blue', <Color.blue: 3>)])))
Attribute(name='__members__', kind='property', defining_class=<class 'plainbox.vendor.enum.EnumMeta'>, object=<property object at 0x7f48c30be998>)
===========================================================================

===========================================================================
Attribute(name='red', kind='data', defining_class=<enum 'Color'>, object=<Color.red: 1>)
Attribute(name='name', kind='data', defining_class=<enum 'Enum'>, object=<plainbox.vendor.enum.DynamicClassAttribute object at 0x7f48c32a6250>)
===========================================================================

F.F..
======================================================================
ERROR: test_subclasses_with_getnewargs_ex (__main__.TestEnum)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "test_enum.py", line 1137, in test_subclasses_with_getnewargs_ex
    test_pickle_dump_load(self.assertEqual, NI5, 5, protocol=(4, 4))
  File "test_enum.py", line 121, in test_pickle_dump_load
    assertion(loads(dumps(source, protocol=protocol)), target)
ValueError: pickle protocol must be <= 3

======================================================================
FAIL: test_inspect_classify_class_attrs (__main__.TestStdLib)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "test_enum.py", line 1713, in test_inspect_classify_class_attrs
    self.fail("result does not equal expected, see print above")
AssertionError: result does not equal expected, see print above

======================================================================
FAIL: test_pydoc (__main__.TestStdLib)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "test_enum.py", line 1655, in test_pydoc
    self.assertEqual(result, expected_text)
AssertionError: "Help on class Color in module __main__:\n\nColor = <enum 'Color'>" != 'Help on class Color in module __main__:\n\nclass Color(plainbox.vendor.enum.Enu [truncated]...
Diff is 1021 characters long. Set self.maxDiff to None to see it.

----------------------------------------------------------------------
Ran 96 tests in 0.216s

FAILED (failures=2, errors=1)

Signed-off-by: Zygmunt Krynicki <zygmunt.krynicki@canonical.com>