checkbox-support: add missing `pyyaml` dependency
```
$ checkbox-cli run com.canonical.certification::connections
Skipped file: /home/ubuntu/dev/canonical/checkbox/providers/base/units/stress/suspend_cycles_reboot.md
===========================[ Running Selected Jobs ]============================
==============[ Running job 1 / 1. Estimated time left: 0:00:01 ]===============
-------------------[ Collect information about connections ]--------------------
ID: com.canonical.certification::connections
Category: com.canonical.certification::information_gathering
... 8< -------------------------------------------------------------------------
Traceback (most recent call last):
  File "/tmp/nest-hb2117fq.192267fd7db6d739bf287b9c356cf937eeb1e4c54befcea50064bd0d2ad11985/snapd_resource.py", line 13, in <module>
    from checkbox_support.snap_utils.asserts import decode
  File "/home/ubuntu/.pyenv/versions/checkbox/lib/python3.10/site-packages/checkbox_support/snap_utils/asserts.py", line 7, in <module>
    import yaml
ModuleNotFoundError: No module named 'yaml'
------------------------------------------------------------------------- >8 ---
Outcome: job failed
Finalizing session that hasn't been submitted anywhere: checkbox-run-2024-03-25T09.29.19
==================================[ Results ]===================================
 ☒ : Collect information about connections
```