Check if os.getenv('USER') returns something before assuming a USER is defined
When checkbox is invoked a systemd service unit running as root, the USER env
variable is not defined leading to a crash in both ctrl and restart modules:

        user_mod = os.getenv('USER').replace('.', '%2E')
    AttributeError: 'NoneType' object has no attribute 'replace'